// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8lp8txFXf2_x0hLyX3jCM1LibqirGxg',
    appId: '1:55996858473:web:66645b75123fc8b10ea2f8',
    messagingSenderId: '55996858473',
    projectId: 'news2471-b4153',
    authDomain: 'news2471-b4153.firebaseapp.com',
    storageBucket: 'news2471-b4153.firebasestorage.app',
    measurementId: 'G-F7G18PCY4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2Kg5jMjKjFMfIuIAZ0obrh0fS5-nwAI',
    appId: '1:55996858473:android:611fcc6ac67310e60ea2f8',
    messagingSenderId: '55996858473',
    projectId: 'news2471-b4153',
    storageBucket: 'news2471-b4153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2UZZysjtmK5RpoTga7agJY56a7-wI_Nw',
    appId: '1:55996858473:ios:36c6c6b8e5ce2b3a0ea2f8',
    messagingSenderId: '55996858473',
    projectId: 'news2471-b4153',
    storageBucket: 'news2471-b4153.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2UZZysjtmK5RpoTga7agJY56a7-wI_Nw',
    appId: '1:55996858473:ios:36c6c6b8e5ce2b3a0ea2f8',
    messagingSenderId: '55996858473',
    projectId: 'news2471-b4153',
    storageBucket: 'news2471-b4153.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh8lp8txFXf2_x0hLyX3jCM1LibqirGxg',
    appId: '1:55996858473:web:d5fc8c045deae6ab0ea2f8',
    messagingSenderId: '55996858473',
    projectId: 'news2471-b4153',
    authDomain: 'news2471-b4153.firebaseapp.com',
    storageBucket: 'news2471-b4153.firebasestorage.app',
    measurementId: 'G-BWN3BMMTJR',
  );
}
